#!/usr/bin/env php
<?php

require_once 'vendor/autoload.php';

use Solital\Console\Config;
use Solital\Core\Console\Command;
use Solital\Core\Kernel\{Application, Console\SolitalCommands};

Application::autoload("vendor/solital/core/src/Resource/Helpers/");

$class_commands = [SolitalCommands::class, Config::class];

(new Command($class_commands))->read($argv, $argv);
