# Enable test in another database
enable_test: false

# Set another database conection to tests
db_test:
  drive: mysql
  host: localhost
  name: teste
  user: root
  pass: 
  sqlite: 

# Set Windows binary dump
dump_windows:
  mysql: C:\wamp64\bin\mysql\mysql8.2.0\bin
  pgsql: C:\Program Files\PostgreSQL\14\bin\pg_dump.exe
  sqlite: 